language: c
notifications:
 irc:
  channels: "anathema.irc.so#anathema"
  use_notice: true
  skip_join: true
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
 - make
 - ctest -V
