liberty
=======

'liberty' is a pseudolibrary of all the common C code I have written for various
projects.  I used to copy-paste large swaths of code with minimal changes to it
and it slowly became awfully painful to synchronize.  The project can be thought
of as a successor to my other C library, libxtnd.

You are supposed to import it as a git submodule and include the main source
file directly everywhere you need it.  Everything is declared "static".  I have
come to the conclusion that this style of C programming suits me the best, as it
allows me to nearly forget about the mess that are header files.

The API is intentionally unstable, which allows for easy refactoring.

All development is done on Linux, but other POSIX-compatible operating systems
should be supported as well.  They have an extremely low priority, however, and
I'm not testing them at all.

License
-------
'liberty' is written by Přemysl Janouch <p.janouch@gmail.com>.

You may use the software under the terms of the ISC license, the text of which
is included within the package, or, at your option, you may relicense the work
under the MIT or the Modified BSD License, as listed at the following site:

http://www.gnu.org/licenses/license-list.html
