liberty
=======

'liberty' is a pseudolibrary of all the common C code I have written for various
projects.  I used to copy-paste large swaths of code with minimal changes to it
and it slowly became awfully painful to synchronize.  The project can be thought
of as a successor to my other C library, libxtnd.

You are supposed to import it as a git submodule and include the main source
file directly everywhere you need it.  Everything is declared "static".  I have
come to the conclusion that this style of C programming suits me the best, as it
allows me to nearly forget about the mess that are header files.

The API is intentionally unstable, which allows for easy refactoring.

All development is done on Linux, but other POSIX-compatible operating systems
should be supported as well.  They have an extremely low priority, however, and
I'm not testing them at all, with the exception of OpenBSD.

Contributing and Support
------------------------
Use this project's GitHub to report any bugs, request features, or submit pull
requests.  If you want to discuss this project, or maybe just hang out with
the developer, feel free to join me at irc://irc.janouch.name, channel #dev.

Bitcoin donations: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
